"""
QGIS Doctor — Bug Reporter (Phase 4).

Genera URL precompilati per segnalare bug su GitHub.
Privacy: sostituisce percorsi con [PATH REMOVED].
"""

import re
import urllib.parse


def _sanitize_paths(text: str) -> str:
    """Sostituisce percorsi di file assoluti con [PATH REMOVED] per privacy."""
    # Unix/macOS absolute paths
    text = re.sub(r"/(?:Users|home|var|tmp|opt|Applications)/[^\s\"\'>]+", "[PATH REMOVED]", text)
    # Windows absolute paths
    text = re.sub(r"[A-Za-z]:\\[^\s\"\'>]+", "[PATH REMOVED]", text)
    return text


def build_github_issue_url(issue, project_summary: dict) -> str:
    """
    Costruisce un URL precompilato per aprire una nuova issue su GitHub.
    Tutti i dati sensibili (percorsi) vengono rimossi.

    Args:
        issue: DiagnosticIssue
        project_summary: dict da DiagnosticsEngine.get_environment_summary()

    Returns:
        str: URL completo per aprire la issue su github.com
    """
    qgis_ver = project_summary.get("qgis_version", "unknown")
    os_str = project_summary.get("os", "unknown")
    project_crs = project_summary.get("project_crs", "unknown")
    n_layers = project_summary.get("n_layers", "?")
    plugins = ", ".join(project_summary.get("active_plugins", [])[:5]) or "none"

    # Sanitizza il technical_detail
    safe_detail = _sanitize_paths(issue.technical_detail or "")
    safe_explanation = _sanitize_paths(issue.explanation or "")

    title = f"[{issue.id}] {issue.title}"

    body = f"""## QGIS Bug Report — generated by QGIS Doctor

### Issue ID
{issue.id} — {issue.title}

### QGIS Environment
- QGIS version: {qgis_ver}
- OS: {os_str}
- Project CRS: {project_crs}
- Number of layers: {n_layers}
- Active plugins: {plugins}

### Description
{safe_explanation}

### Technical Details
```
{safe_detail}
```

### Steps to Reproduce
<!-- Please describe the steps that led to this issue -->
1.
2.
3.

### Expected Behavior
<!-- What did you expect to happen? -->

### Actual Behavior
<!-- What actually happened? -->

---
*Reported via [QGIS Doctor](https://github.com/search?q=qgis+doctor+plugin) diagnostic plugin*
"""

    params = urllib.parse.urlencode({
        "title": title[:200],  # GitHub limita il titolo
        "body": body,
        "labels": "bug",
    })

    return f"https://github.com/qgis/QGIS/issues/new?{params}"


def build_report_url_for_issue(issue, project_summary: dict) -> str:
    """
    Versione più compatta per issue non-bug (es. feature request o domanda).
    """
    title = f"[Question] {issue.title}"
    safe_detail = _sanitize_paths(issue.technical_detail or "")
    qgis_ver = project_summary.get("qgis_version", "unknown")

    body = f"""## Question about: {issue.id} — {issue.title}

QGIS version: {qgis_ver}
OS: {project_summary.get('os', 'unknown')}

{_sanitize_paths(issue.explanation or '')}

Technical detail:
```
{safe_detail}
```
"""
    params = urllib.parse.urlencode({"title": title[:200], "body": body})
    return f"https://github.com/qgis/QGIS/issues/new?{params}"
